name: Pre-commit Checks

# Run the workflow on push and pull request events for any branch
on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # You can specify the Python version your project uses

    # Install dependencies including pre-commit
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    # Install additional project dependencies if required
    # If you have a requirements.txt or requirements-dev.txt file
    - name: Install project dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

    # Run pre-commit on all files
    - name: Run pre-commit checks
      run: pre-commit run --all-files
